export default function AboutPage() {
  return (
    <main className="min-h-screen bg-slate-50">

      {/* HEADER */}
      <div className="bg-[#1D4ED8] text-white py-10">
        <div className="max-w-5xl mx-auto px-6">
          <h1 className="text-4xl font-bold">About Us</h1>

          <p className="mt-3 text-blue-100 text-sm">
            Learn more about Mega Tools Web and our mission.
          </p>
        </div>
      </div>

      {/* CONTENT */}
      <div className="max-w-5xl mx-auto px-6 py-10">

        <div className="bg-white rounded-2xl shadow-sm border p-8 space-y-8">

          {/* INTRO */}
          <section>
            <h2 className="text-2xl font-bold mb-3 text-gray-800">
              Welcome to Mega Tools Web
            </h2>

            <p className="text-gray-700 leading-7">
              Mega Tools Web is a growing collection of free online tools
              and premium desktop utilities designed to help users perform
              everyday digital tasks quickly and efficiently.
            </p>

            <p className="text-gray-700 leading-7 mt-4">
              Our platform includes calculators, converters, developer tools,
              image utilities, text tools, and premium productivity software —
              all accessible from a simple and compact interface.
            </p>
          </section>

          {/* MISSION */}
          <section>
            <h2 className="text-2xl font-bold mb-3 text-gray-800">
              Our Mission
            </h2>

            <p className="text-gray-700 leading-7">
              Our mission is to provide fast, lightweight, and useful tools
              that save time and improve productivity for students,
              professionals, developers, and everyday users.
            </p>
          </section>

          {/* WHAT WE OFFER */}
          <section>
            <h2 className="text-2xl font-bold mb-3 text-gray-800">
              What We Offer
            </h2>

            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Free online calculators and converters</li>
              <li>Developer productivity tools</li>
              <li>Image editing and optimization utilities</li>
              <li>Text formatting and analysis tools</li>
              <li>Premium downloadable desktop software</li>
              <li>Simple and responsive user interface</li>
            </ul>
          </section>

          {/* FOUNDER */}
          <section>
            <h2 className="text-2xl font-bold mb-3 text-gray-800">
              Founder Information
            </h2>

            <p className="text-gray-700 leading-7">
              This website was created and maintained by: 
            </p>

            <div className="mt-4 bg-slate-100 rounded-xl p-5 border space-y-2 text-sm">

              <div>
                <span className="font-semibold">Name:</span>
                {" "}
                CLASSICSOFT TECHNOLOGIES PRIVATE LIMITED
              </div>

              <div>
                <span className="font-semibold">Location:</span>
                {" "}
                MUMBAI, INDIA
              </div>

              <div>
                <span className="font-semibold">Email:</span>
                {" "}
                info@classicsofttechnologies.com
              </div>

              <div>
                <span className="font-semibold">Website:</span>
                {" "}
                https://www.classicsofttechnologies.com
              </div>

            </div>
          </section>

          {/* DISCLAIMER */}
          <section>
            <h2 className="text-2xl font-bold mb-3 text-gray-800">
              Disclaimer
            </h2>

            <p className="text-gray-700 leading-7">
              While we strive to provide accurate and reliable tools,
              Mega Tools Web does not guarantee the completeness,
              reliability, or accuracy of the results generated by
              the tools on this website. Users should verify important
              calculations and outputs independently.
            </p>
          </section>

        </div>

      </div>

    </main>
  );
}